[project]
name = "example"
version = "0.1.0"
description = "Django Tutorial"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django==5.1.1",
    "ruff==0.6.9",
    "django-debug-toolbar==4.4.6",
    "psycopg2-binary==2.9.9",
]
